### ISSUE TITLE
(🐞) `poetry export` silently does nothing when `--extras` is not a defined extra

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry-plugin-export#101]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: windows 10
- **Poetry version**: 1.2.0rc1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
```toml
[tool.poetry]
name = "test"
version = "1"
description = ""
authors = []

[tool.poetry.extras]
a = ["urllib3"]
b = ["tomli"]

[tool.poetry.dependencies]
python = "^3.10"
urllib3 = { version ="*", optional=true}
tomli  = { version ="*", optional=true}
```

## Issue
```
👉 poetry export --extras "AMONGUS"

👉 poetry install --extras "AMONGUS" 
Installing dependencies from lock file

Extra [AMONGUS] is not specified.        
```

I would expect an error here regarding the fact that there is no extra named "AMONGUS".

`poetry install` correctly shows an error here.
