### ISSUE TITLE
`poetry export --without` exports optional dependency groups

### ISSUE THREAD

**Issue by pmav99** [python-poetry/poetry-plugin-export#11]
This is similar to https://github.com/python-poetry/poetry/issues/4577

if you use `--without`, then the optional dependencies get exported unless you explicitly use `--without` on them

``` toml
[tool.poetry]
name = "aaa"
version = "0.1.0"
description = ""
authors = ["pmav99 <pmav99@mail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.test]
optional = true
[tool.poetry.group.foo]
optional = true

[tool.poetry.group.test.dependencies]
pytest= "*"

[tool.poetry.group.foo.dependencies]
black = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

E.g. here we use `--without` on a non-existing group and we notice that both optional groups got exported.
```
$ poetry export --without-hashes --without gibberish | ag 'pytest|black'
black==21.9b0; python_full_version >= "3.6.2"
pytest==6.2.5; python_version >= "3.6"
```

If we explicitly use `--without` on either one of the optional groups, then they are indeed excluded from the output
```
$ poetry export --without-hashes --without gibberish --without test| ag 'pytest|black'
black==21.9b0; python_full_version >= "3.6.2"
```

and 
```
$ poetry export --without-hashes --without gibberish --without foo | ag 'pytest|black'
pytest==6.2.5; python_version >= "3.6"
```
