### ISSUE TITLE
Dependency walk failed with python-specific package versions

### ISSUE THREAD

**Issue by npalmius** [python-poetry/poetry-plugin-export#187]
This may be related to some of the other 'Dependency walk failed' issues, but I am posting it as an additional test case.

- **Poetry version**: tested with 1.3.2 and 1.4.0 (was working in 1.1.15)
- **Python version**: 3.7.16
- **OS version and name**: Debian GNU/Linux 10 (buster)
- **pyproject.toml**:

```toml
[tool.poetry]
name = "test"
version = "1.0.0"
description = ""
authors = ["test"]

[tool.poetry.dependencies]
python = "^3.7"
arctic = "==1.70.0"
pandas = [
    { version = "==0.23.4", python = "<3.9" },
    { version = "~=1.0", python = ">=3.9" }
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

With the above pyproject.toml, `poetry export` fails with
```
Dependency walk failed at pandas
```

Changing the `arctic` dependency (which also has a dependency on `pandas`) to
```
arctic = [
    { version = "==1.70.0", python = "<3.9" },
    { version = "==1.70.0", python = ">=3.9" }
]
```
resolves the issue as a workaround.
