### ISSUE TITLE
poetry does not export url from legacy type source

### ISSUE THREAD

**Issue by LorhanSohaky** [python-poetry/poetry-plugin-export#198]
I have a project with public dependencies and other dependencies on a private index

I expected that when exporting the dependencies the ones that are private include the url for them to be installed

For example:
pyproject.toml
```toml
[tool.poetry]
name = "example"
version = "0.1.0"
description = "Test"
readme = "README.md"

[[tool.poetry.source]]
name = "codeartifact"
url = "https://codeartifact.us-east-1.amazonaws.com/pypi/example/"
default = false
secondary = true

[tool.poetry.dependencies]
python = "^3.8.1"
requests = "^2.28.2"
private-package = {version = "^2.0.0", source = "codeartifact"}


[build-system]
requires = ["poetry-core", "poetry>=1.2.2"]
build-backend = "poetry.core.masonry.api"
```

## Simplified output

```
requests==2.28.2 ; python_full_version >= "3.8.1" and python_version < "4"
private-package==2.0.0 ; python_full_version >= "3.8.1" and python_full_version < "4.0.0"
````

## Expected output
Something like that
```
requests==2.28.2 ; python_full_version >= "3.8.1" and python_version < "4"
private-package==2.0.0 @ https://codeartifact.us-east-1.amazonaws.com/pypi/example; python_full_version >= "3.8.1" and python_full_version < "4.0.0"
````
