### ISSUE TITLE
Warning on pre-commit hook

### ISSUE THREAD

**Issue by dga-nagra** [python-poetry/poetry-plugin-export#249]
I am using the following pre-commit hook:

``` yaml
  - repo: https://github.com/python-poetry/poetry
    rev: '1.6.0'  # add version here
    hooks:
      - id: poetry-check
        args: [--no-cache]
        language_version: python3.9
      - id: poetry-lock
        args: [--no-cache]
        language_version: python3.9

  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: '1.6.0'  # add version here
    hooks:
      - id: poetry-export
        args: ["--no-cache", "-f", "requirements.txt", "-o", "requirements.txt"]
        language_version: python3.9
```

and receiving the following warning:
![image](https://github.com/python-poetry/poetry-plugin-export/assets/147379886/c3dabeef-30f0-4e14-9ad1-f7b055b2a8c2)

It seems that it is not using the plugin and instead use the deprecated `poetry export` command
