### ISSUE TITLE
[1.8] Not compatible with pyproject.toml/poetry.lock accepted/generated by poetry 1.8 (package-mode=false)

### ISSUE THREAD

**Issue by akshetpandey** [python-poetry/poetry-plugin-export#261]
After adding `package-mode = false` to pyproject.toml and removing now optional fields, I get:
```
The Poetry configuration is invalid:
  - data must contain ['authors', 'description', 'version'] properties
  - Additional properties are not allowed ('package-mode' was unexpected)
```

**Comment by dimbleby** [comment]
works fine.

I suppose you have not got the latest version of poetry or poetry-core in your installation, and should update.

please close

**Comment by akshetpandey** [comment]
my pre-commit file:

```
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.0'
    hooks:
      - id: poetry-check
  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: '1.6.0'
    hooks:
      - id: poetry-export
        args: ['-f', 'requirements.txt', '--without-hashes', '-o', 'requirements.txt']
```

pre-commit run --all-files:
```
poetry-export............................................................Failed
- hook id: poetry-export
- exit code: 1

The Poetry configuration is invalid:
  - data must contain ['authors', 'description', 'version'] properties
  - Additional properties are not allowed ('package-mode' was unexpected)
```
