### ISSUE TITLE
Duplicate dependency export

### ISSUE THREAD

**Issue by pwoolvett** [python-poetry/poetry-plugin-export#28]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: elementary OS 5.0 Juno
- **Poetry version**:1.0.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:
<details>
  <summary>pyproject.toml</summary>

```toml
[tool.poetry]
name = "tmpoetry"
version = "0.1.0"
description = "sdfg"
authors = ["Author <author@mail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
mypy = "^0.701"
pylint = "^2.3"
```
  </details>

## Issue

* When a (sub)dependency has different requirements for different python versions, it appears twice in `poetry.lock`. In itself this is no problem, but `poetry export` generates duplicate entries.

* In this use case, the command `poetry add` fails because said library has "conflifting"  versions.
(try `poetry add astroid`)
