### ISSUE TITLE
Relative installs with `develop = true` not exporting to requirements.txt correctly

### ISSUE THREAD

**Issue by nickroberts** [python-poetry/poetry-plugin-export#287]
When exporting with a relative package, with `develop = true`, the `requirements.txt` file is not created correctly.

`pyproject.toml`
```toml
[tool.poetry.dependencies]
package-name = { path = "../relative/path/to/package-name", develop = true }
```

`requirements.txt` with `1.7.1`
```txt
package-name @ file:///absolute/path/to/package-name ; python_version >= "3.10" and python_version < "4.0"
```

`requirements.txt` with `1.8.0`
```txt
-e file:///absolute/path/to/package-name ; python_version >= "3.10" and python_version < "4.0"
```

When installing via pip, it does not copy the package files into the target directory. It puts the dist-info folder, and a `package_name.pth` file.
