### ISSUE TITLE
Question about export of dependency with extra, e.g. httpx[http2], in Python 1.8.5 vs this plugin

### ISSUE THREAD

**Issue by jrobbins-LiveData** [python-poetry/poetry-plugin-export#326]
I attempted to create two identical projects, one using Poetry 1.8.5 and the other using Poetry 2.1.1 with this plugin.

The folder trees of both are analogous:

```
│   poetry.lock
│   pyproject.toml
│   README.md
│   reqs.txt
│
└───src
    └───one_eight_five
            __init__.py
```

with this `pyproject.toml`

```toml
[tool.poetry]
name = "one-eight-five"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "one_eight_five", from = "src"}]

[tool.poetry.dependencies]
python = "^3.13"
httpx = {extras = ["http2"], version = "*"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

vs

```
│   poetry.lock
│   pyproject.toml
│   README.md
│   reqs.txt
│
└───src
    └───two_one_one
            __init__.py
```

with this `pyproject.toml`

```toml
[project]
name = "two-one-one"
version = "0.1.0"
description = "test"
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0.0"
dependencies = [
    "httpx[http2]"
]

[tool.poetry]
requires-poetry = ">=2.1"
packages = [{include = "two_one_one", from = "src"}]

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
```

I did a `poetry export --without-hashes --without-urls` of both projects and have attached the output below.  The question is that the version 1.8.5 export has this line:

`httpx[http2]==0.28.1 ; python_version >= "3.13" and python_version < "4.0"`  

whereas the version 2.1.1 export has this line:

`httpx==0.28.1 ; python_version >= "3.13" and python_full_version < "4.0.0"`

Note that the `[http2]` is missing.  Since both requirements files have a line for `h2`, which is all that `[http2]` ends up meaning for the `httpx` package, I guess I haven't lost anything due to that missing `[http2]` if I go use the requirements file in a Dockerfile build process.  But the difference was confusing to me, and I was hoping to hear from someone who knows how this is supposed to work.  Ought the two requirements files show the same thing?

When I `poetry build` both projects, the `.whl` files' `METADATA` each contain this line:

```
Requires-Dist: httpx[http2]
```

[reqs_185.txt](https://github.com/user-attachments/files/18897513/reqs_185.txt)

[reqs_211.txt](https://github.com/user-attachments/files/18897516/reqs_211.txt)
